### PR TITLE
Logo-Design-By-Sowmiya

### LINKED ISSUE #59: Create Logo
Cc: @OSCA-Ado-Ekiti 
We need a simple and more techie logo for Hacktoberfest Ekiti web app.

This is the link to the previous one done last year. Check here 
https://github.com/OSCA-Ado-Ekiti/Hacktoberfest2021-Ekiti/issues/50

Pls make sure these are included in your submission;
- The idea behind your logo.
- Your sketch
- Black and white version of the logo
- 1-3 Mock-ups to show how it will look.
- file formats such as SVG, JPEG, PNG (for now)

### PR DESCRIPTION
**Pull request by sowmiyeh**
Description
This PR adds one new logo for this repo.

Related Issue
Closes #59 

Acceptance Criteria

- [x] File Formats: SVG, PNG(Transparent), JPEG
- [x] The idea behind your logo + 1-3 Mock-ups to show how it will look.
- [x] Black and white version of the logo

Logo Desc

Figma Link - https://www.figma.com/file/p6nwiuq0TbY9SyeYXkqMUQ/Hacktoberfest2022-Ekiti-Logo?node-id=0%3A1

### CODE REVIEW

**Comment by sowmiyeh** [comment]
Hi @saintmalik Please check and merge it, Thanks!

**Comment by OSCA-Ado-Ekiti** [comment]
lgtm

**Comment by sowmiyeh** [comment]
> lgtm

Thank you so much!

**Comment by Victorayo** [comment]
> Description This PR adds one new logo for this repo.
> 
> Related Issue Closes #59
> 
> Acceptance Criteria
> 
> * [x]  File Formats: SVG, PNG(Transparent), JPEG
> * [x]  The idea behind your logo + 1-3 Mock-ups to show how it will look.
> * [x]  Black and white version of the logo
> 
> Logo Desc
> 
> Figma Link - https://www.figma.com/file/p6nwiuq0TbY9SyeYXkqMUQ/Hacktoberfest2022-Ekiti-Logo?node-id=0%3A1

I'm impressed @sowmiya-venkatesan . Thanks for this submission

**Pull request merged**
